
name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 4a15ab7cd0a4b78a7356e5f488d5345b8d314549
      
    - name: Install dependencies
      run: |
        sudo apt-get install -y wget
        wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.20.tar.gz
        tar xf libsodium-1.0.20.tar.gz
        
    - name: Build source
      run: |
       cd libsodium-1.0.20
       ./configure
       make && make check
